settings:
  enable_filter: true

allowlist:
  - 阿瓦隆
  - 刺客
  - 殺手
  - 革命
  - 審判
  - 戰爭
  - 冷戰熱鬥
  - 美麗島風雲
  - 台北大空襲
  - 秘密希特勒
  - 社會主義

blocklist:
  - 總統
  - 選舉
  - 政黨
  - 民進黨
  - 國民黨
  - 民眾黨
  - 共產黨
  - 習近平
  - 賴清德
  - 川普
  - 拜登
  - 台獨
  - 統一
  - 兩岸
  - 政治
  - 髒話
